### ISSUE TITLE
deploy and link db

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/docker-receval#2]
- [x] connect dockerhub
- [x] create username, password and schema for django
- [x] deploy on dke01
- [x] configure traefik

**Comment by physikerwelt** [comment]
now on dockerhub https://hub.docker.com/r/aggipp/receval

**Comment by physikerwelt** [comment]
... still working on a PR for the deployment... https://github.com/ag-gipp/srv-dke01/pull/93

**Comment by physikerwelt** [comment]
see https://github.com/ag-gipp/srv-dke01/pull/93/files#diff-072e81fe88d9b23fe00fc189279936a6R37 for database information

**Comment by physikerwelt** [comment]
PR for config change is done... waiting for code review

**Comment by physikerwelt** [comment]
The code is deployed. However, the service can not be started. I can't figure out the problem
```
physikerwelt@dke01:~/d$ docker-compose run receval_app /bin/bash
Starting zblpostgres ... done
root@0afcccc38704:/app# ping zblpostgres
PING zblpostgres (172.26.0.29) 56(84) bytes of data.
64 bytes from zblpostgres.docker_default (172.26.0.29): icmp_seq=1 ttl=64 time=0.321 ms
64 bytes from zblpostgres.docker_default (172.26.0.29): icmp_seq=2 ttl=64 time=0.082 ms
64 bytes from zblpostgres.docker_default (172.26.0.29): icmp_seq=3 ttl=64 time=0.049 ms
64 bytes from zblpostgres.docker_default (172.26.0.29): icmp_seq=4 ttl=64 time=0.079 ms
^C
--- zblpostgres ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 33ms
rtt min/avg/max/mdev = 0.049/0.132/0.321/0.110 ms
root@0afcccc38704:/app# echo $DATABASE_URL
postgresql+psycopg2://malte:malte@zblpostgres/malte
root@0afcccc38704:/app# ls
Dockerfile   Procfile   django.log              docker-compose.yml  receval           runtime.txt
LICENSE.txt  README.md  docker-compose.dev.yml  manage.py           requirements.txt  sbin
root@0afcccc38704:/app# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/site-packages/configurations/importer.py", line 153, in load_module
    mod = imp.load_module(fullname, *self.location)
  File "/usr/local/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/receval/settings.py", line 17, in <module>
    class Base(Configuration):
  File "/app/receval/settings.py", line 172, in Base
    db_from_env = dj_database_url.config(conn_max_age=500, default='sqlite:///db.sqlite3')
  File "/usr/local/lib/python3.7/site-packages/dj_database_url.py", line 55, in config
    config = parse(s, engine, conn_max_age, ssl_require)
  File "/usr/local/lib/python3.7/site-packages/dj_database_url.py", line 103, in parse
    engine = SCHEMES[url.scheme] if engine is None else engine
KeyError: 'postgresql+psycopg2'

**Comment by malteos** [comment]
`postgresql+psycopg2`is an invalid schema. Try `postgres://USER:PASSWORD@HOST:PORT/NAME` instead. 

The syntax of `DJANGO_ZBMATH_DATABASE_URL` (sqlalchemy) and `DATABASE_URL` (django) is slightly different.

**Comment by physikerwelt** [comment]
@malteos can you have a look at the new PR https://github.com/ag-gipp/srv-dke01/pull/96

**Comment by physikerwelt** [comment]
it is now running at 

zbl-receval.formulasearchengine.com

login information

https://github.com/ag-gipp/srv-dke01/blob/27843582363b8282ac4220d53769606f142c9783/docker/traefik/conf/malte.yml#L16
